### ISSUE TITLE
Image Generation

### ISSUE THREAD

**Issue by YixuanGao98** [rishubhpar/PreciseControl#3]
I want to generate an image.

However, when I run: "bash ./02_start_test.sh "./weights/v2-1_512-ema-pruned.ckpt" "./infer_images/example_prompt_1.txt" id_name "0 0 0 0" True 4 49 0.2 image_name.jpg ", the following problem occurs:

Interpolate ids: [0, 0, 0, 0]
Seed set to 42
Traceback (most recent call last):
  File "/home/gyx/code/T2I/PreciseControl-main/scripts/stable_txt2img_testing.py", line 687, in <module>
    main()
  File "/home/gyx/code/T2I/PreciseControl-main/scripts/stable_txt2img_testing.py", line 293, in main
    config = OmegaConf.load(f"{opt.config}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gyx/.local/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'PreciseControl-main/logs/id_name/configs/id_name-project.yaml'

**Comment by sachidanandvs** [comment]
Hi, thank you for your interest, while giving the arguments, the id_name should be name of folder saved in logs folder, this will be generated after you finetune for a specific id. For, example we have provided cook finetuned weights folder. After you put that in logs. you should run `bash ./02_start_test.sh "./weights/v2-1_512-ema-pruned.ckpt" "./infer_images/example_prompt_1.txt" cook "0 0 0 0" True 4 49 0.2 cook.jpg`. Let me know if the issue is still there.
